
export const symptomsDatabase: Record<string, string[]> = {
  "headache": ["Aspirin", "Ibuprofen", "Acetaminophen", "Paracetamol"],
  "fever": ["Acetaminophen", "Ibuprofen", "Paracetamol"],
  "cough": ["Dextromethorphan", "Guaifenesin", "Benzonatate","Cough syrup"],
  "sore throat": ["Lozenges", "Chloraseptic spray", "Ibuprofen"],
  "allergies": ["Cetirizine", "Loratadine", "Fexofenadine"],
  "nausea": ["Dramamine", "Pepto-Bismol", "Ginger supplements"],
  "muscle pain": ["Ibuprofen", "Naproxen", "Acetaminophen"],
  "insomnia": ["Melatonin", "Diphenhydramine", "Doxylamine"],
  "heartburn": ["Antacids", "Ranitidine", "Omeprazole"],
  "diarrhea": ["Loperamide", "Bismuth subsalicylate", "Probiotics"],
  "constipation": ["Psyllium", "Docusate", "Polyethylene glycol"],
  "sinus congestion": ["Pseudoephedrine", "Oxymetazoline", "Fluticasone"],
  "back pain": ["Ibuprofen", "Naproxen", "Acetaminophen"],
  "toothache": ["Benzocaine", "Ibuprofen", "Acetaminophen"],
  "earache": ["Acetaminophen", "Ibuprofen", "Benzocaine ear drops"],
  "rash": ["Hydrocortisone cream", "Antihistamines", "Calamine lotion"],
  "anxiety": ["Diazepam", "Alprazolam", "Lorazepam"],
  "depression": ["Fluoxetine", "Sertraline", "Escitalopram"],
  "migraine": ["Sumatriptan", "Rizatriptan", "Ergotamine"],
  "indigestion": ["Antacids", "Simethicone", "Famotidine"],
  "menstrual cramps": ["Ibuprofen", "Naproxen", "Acetaminophen"],
  "acid reflux": ["Omeprazole", "Esomeprazole", "Lansoprazole"],
  "high blood pressure": ["Lisinopril", "Amlodipine", "Metoprolol"],
  "diabetes": ["Metformin", "Insulin", "Glipizide"],
  "asthma": ["Albuterol", "Fluticasone", "Montelukast"],
  "arthritis": ["Ibuprofen", "Naproxen", "Celecoxib"],
  "common cold": ["Phenylephrine", "Guaifenesin", "Dextromethorphan"],
  "flu": ["Oseltamivir", "Zanamivir", "Acetaminophen"],
  "pneumonia": ["Amoxicillin", "Azithromycin", "Levofloxacin"],
  "bronchitis": ["Albuterol", "Prednisone", "Guaifenesin"],
  "urinary tract infection": ["Ciprofloxacin", "Nitrofurantoin", "Trimethoprim"],
  "yeast infection": ["Fluconazole", "Clotrimazole", "Miconazole"],
  "hemorrhoids": ["Hydrocortisone cream", "Witch hazel", "Phenylephrine"],
  "gout": ["Allopurinol", "Colchicine", "Indomethacin"],
  "osteoporosis": ["Alendronate", "Risedronate", "Calcium supplements"],
  "high cholesterol": ["Atorvastatin", "Simvastatin", "Rosuvastatin"],
  "thyroid disorder": ["Levothyroxine", "Liothyronine", "Methimazole"],
  "adhd": ["Methylphenidate", "Amphetamine", "Dexmethylphenidate"],
  "bipolar disorder": ["Lithium", "Valproate", "Lamotrigine"],
  "schizophrenia": ["Risperidone", "Olanzapine", "Quetiapine"],
  "epilepsy": ["Phenytoin", "Carbamazepine", "Valproate"],
  "parkinson's disease": ["Levodopa", "Carbidopa", "Pramipexole"],
  "alzheimer's disease": ["Donepezil", "Rivastigmine", "Memantine"],
  "hiv": ["Tenofovir", "Emtricitabine", "Efavirenz"],
  "hepatitis c": ["Sofosbuvir", "Ledipasvir", "Daclatasvir"],
  "tuberculosis": ["Isoniazid", "Rifampin", "Pyrazinamide"],
  "malaria": ["Chloroquine", "Hydroxychloroquine", "Artemether"],
  "lyme disease": ["Doxycycline", "Amoxicillin", "Cefuroxime"],
  "chickenpox": ["Acetaminophen", "Acyclovir", "Calamine lotion"],
  "shingles": ["Acyclovir", "Valacyclovir", "Famciclovir"],
  "herpes": ["Acyclovir", "Valacyclovir", "Famciclovir"],
  "gonorrhea": ["Ceftriaxone", "Azithromycin", "Doxycycline"],
  "syphilis": ["Penicillin", "Doxycycline", "Tetracycline"],
  "chlamydia": ["Azithromycin", "Doxycycline", "Erythromycin"],
  "trichomoniasis": ["Metronidazole", "Tinidazole", "Secnidazole"],
  "scabies": ["Permethrin", "Ivermectin", "Lindane"],
  "ringworm": ["Clotrimazole", "Terbinafine", "Miconazole"],
  "athlete's foot": ["Clotrimazole", "Terbinafine", "Miconazole"],
  "jock itch": ["Clotrimazole", "Terbinafine", "Miconazole"],
  "eczema": ["Hydrocortisone cream", "Tacrolimus", "Pimecrolimus"],
  "psoriasis": ["Corticosteroids", "Vitamin D analogs", "Methotrexate"],
  "rosacea": ["Metronidazole", "Azelaic acid", "Ivermectin"],
  "acne": ["Benzoyl peroxide", "Salicylic acid", "Retinoids"],
  "warts": ["Salicylic acid", "Cryotherapy", "Imiquimod"],
  "cold sores": ["Acyclovir", "Valacyclovir", "Famciclovir"],
  "sunburn": ["Aloe vera", "Hydrocortisone cream", "Ibuprofen"],
  "poison ivy": ["Hydrocortisone cream", "Calamine lotion", "Diphenhydramine"],
  "food poisoning": ["Loperamide", "Bismuth subsalicylate", "Probiotics"],
  "motion sickness": ["Dramamine", "Meclizine", "Scopolamine"],
  "vertigo": ["Meclizine", "Diazepam", "Promethazine"],
  "tinnitus": ["Alprazolam", "Gabapentin", "Acamprosate"],
  "glaucoma": ["Timolol", "Latanoprost", "Brimonidine"],
  "cataracts": ["Surgery", "Artificial tears", "Antioxidants"],
  "macular degeneration": ["Anti-VEGF injections", "Lutein", "Zeaxanthin"],
  "dry eyes": ["Artificial tears", "Cyclosporine", "Lifitegrast"],
  "conjunctivitis": ["Antibiotic eye drops", "Antihistamine eye drops", "Artificial tears"],
  "stye": ["Warm compresses", "Erythromycin ointment", "Chloramphenicol"],
  "blepharitis": ["Warm compresses", "Antibiotic ointment", "Artificial tears"],
  "keratitis": ["Antibiotic eye drops", "Antifungal eye drops", "Antiviral eye drops"],
  "iritis": ["Steroid eye drops", "Cycloplegic eye drops", "Oral steroids"],
  "retinal detachment": ["Surgery", "Laser therapy", "Cryotherapy"],
  "diabetic retinopathy": ["Laser therapy", "Anti-VEGF injections", "Vitrectomy"],
  "hypertensive retinopathy": ["Blood pressure control", "Laser therapy", "Vitrectomy"],
  "optic neuritis": ["Steroids", "Immunosuppressants", "Plasmapheresis"],
  "papilledema": ["Acetazolamide", "Steroids", "Surgery"],
  "amblyopia": ["Patching", "Atropine drops", "Vision therapy"],
  "strabismus": ["Prism glasses", "Vision therapy", "Surgery"],
  "nystagmus": ["Baclofen", "Gabapentin", "Surgery"],
  "ptosis": ["Surgery", "Neostigmine", "Pyridostigmine"],
  "chalazion": ["Warm compresses", "Steroid injections", "Surgery"],
  "episcleritis": ["Artificial tears", "Steroid eye drops", "NSAIDs"],
  "scleritis": ["Steroids", "Immunosuppressants", "NSAIDs"],
  "uveitis": ["Steroid eye drops", "Cycloplegic eye drops", "Oral steroids"],
  "endophthalmitis": ["Antibiotic injections", "Steroid injections", "Vitrectomy"],
  "orbital cellulitis": ["Antibiotics", "Steroids", "Surgery"],
  "presbyopia": ["Reading glasses", "Bifocals", "Progressive lenses"],
  "myopia": ["Glasses", "Contact lenses", "LASIK"],
  "hyperopia": ["Glasses", "Contact lenses", "LASIK"],
  "astigmatism": ["Glasses", "Contact lenses", "LASIK"],
  "color blindness": ["Color filters", "Tinted lenses", "Gene therapy"],
  "night blindness": ["Vitamin A", "Retinal supplements", "Gene therapy"],
  "acidosis": ["Sodium bicarbonate", "Insulin", "Dialysis"],
  "alkalosis": ["Ammonium chloride", "Potassium chloride", "Hydrochloric acid"],
  "anemia": ["Iron supplements", "Vitamin B12", "Folic acid"],
  "angina": ["Nitroglycerin", "Beta-blockers", "Calcium channel blockers"],
  "appendicitis": ["Antibiotics", "Surgery", "Pain relievers"],
  "bedsores": ["Antibiotic ointments", "Hydrocolloid dressings", "Alginate dressings"],
  "bell's palsy": ["Prednisone", "Antiviral drugs", "Eye drops"],
  "bladder infection": ["Ciprofloxacin", "Nitrofurantoin", "Trimethoprim"],
  "bruxism": ["Mouth guards", "Muscle relaxants", "Botox injections"],
  "bursitis": ["Ibuprofen", "Corticosteroid injections", "Physical therapy"],
  "carpal tunnel syndrome": ["Wrist splints", "Corticosteroid injections", "Surgery"],
  "celiac disease": ["Gluten-free diet", "Vitamin supplements", "Probiotics"],
  "chronic fatigue syndrome": ["Cognitive behavioral therapy", "Graded exercise therapy", "Antidepressants"],
  "cirrhosis": ["Diuretics", "Beta-blockers", "Liver transplant"],
  "cluster headaches": ["Oxygen therapy", "Triptans", "Verapamil"],
  "crohn's disease": ["Anti-inflammatory drugs", "Immunosuppressants", "Biologics"],
  "cystic fibrosis": ["Bronchodilators", "Mucus thinners", "Antibiotics"],
  "dementia": ["Donepezil", "Memantine", "Rivastigmine"],
  "diverticulitis": ["Antibiotics", "Pain relievers", "High-fiber diet"],
  "endometriosis": ["Hormonal therapy", "Pain relievers", "Surgery"],
  "fibromyalgia": ["Pregabalin", "Duloxetine", "Milnacipran"],
  "gallstones": ["Ursodiol", "Pain relievers", "Surgery"],
  "gastroenteritis": ["Oral rehydration salts", "Antibiotics", "Antiemetics"],
  "gingivitis": ["Antibacterial mouthwash", "Dental cleaning", "Antibiotics"],
  "hepatitis b": ["Tenofovir", "Entecavir", "Interferon"],
  "hypothyroidism": ["Levothyroxine", "Liothyronine", "Armour Thyroid"],
  "irritable bowel syndrome": ["Fiber supplements", "Antispasmodics", "Probiotics"],
  "kidney stones": ["Pain relievers", "Alpha-blockers", "Lithotripsy"],
  "lupus": ["Hydroxychloroquine", "Corticosteroids", "Immunosuppressants"],
  "multiple sclerosis": ["Interferon beta", "Glatiramer acetate", "Natalizumab"],
  "obesity": ["Orlistat", "Phentermine", "Liraglutide"],
  "osteomyelitis": ["Antibiotics", "Surgery", "Hyperbaric oxygen therapy"],
  "pancreatitis": ["Pain relievers", "Antibiotics", "Pancreatic enzymes"],
  "peptic ulcer": ["Proton pump inhibitors", "Antibiotics", "Antacids"],
  "peripheral neuropathy": ["Gabapentin", "Pregabalin", "Tricyclic antidepressants"],
  "pneumothorax": ["Chest tube", "Oxygen therapy", "Surgery"],
  "polio": ["Physical therapy", "Pain relievers", "Ventilator support"],
  "prostatitis": ["Antibiotics", "Alpha-blockers", "Anti-inflammatory drugs"],
  "rheumatoid arthritis": ["Methotrexate", "Hydroxychloroquine", "Biologics"],
  "scleroderma": ["Immunosuppressants", "Calcium channel blockers", "Proton pump inhibitors"],
  "sepsis": ["Antibiotics", "IV fluids", "Vasopressors"],
  "sickle cell anemia": ["Hydroxyurea", "Pain relievers", "Blood transfusions"],
  "sleep apnea": ["CPAP machine", "Oral appliances", "Surgery"],
  "tendinitis": ["Ibuprofen", "Corticosteroid injections", "Physical therapy"],
  "tetanus": ["Tetanus immune globulin", "Antibiotics", "Muscle relaxants"],
  "thrombosis": ["Anticoagulants", "Thrombolytics", "Compression stockings"],
  "ulcerative colitis": ["Aminosalicylates", "Corticosteroids", "Immunosuppressants"],
  "varicose veins": ["Compression stockings", "Sclerotherapy", "Surgery"],
  "vitamin deficiency": ["Vitamin supplements", "Dietary changes", "Injections"],
  "whooping cough": ["Antibiotics", "Cough suppressants", "Vaccination"],
  "yellow fever": ["Supportive care", "Vaccination", "Fluid therapy"],
  "acid reflux in infants": ["Gaviscon Infant", "Ranitidine", "Omeprazole"],
  "adenovirus infection": ["Supportive care", "Hydration", "Antipyretics"],
  "adrenal fatigue": ["Adaptogenic herbs", "Vitamin C", "Pantothenic acid"],
  "agoraphobia": ["Cognitive behavioral therapy", "SSRIs", "Benzodiazepines"],
  "alcohol withdrawal": ["Benzodiazepines", "Thiamine", "Anticonvulsants"],
  "amyloidosis": ["Chemotherapy", "Immunosuppressants", "Organ transplant"],
  "anal fissure": ["Nitroglycerin ointment", "Lidocaine", "Surgery"],
  "anaphylaxis": ["Epinephrine", "Antihistamines", "Corticosteroids"],
  "ankylosing spondylitis": ["NSAIDs", "Biologics", "Physical therapy"],
  "anthrax": ["Ciprofloxacin", "Doxycycline", "Antitoxin"],
  "aortic aneurysm": ["Beta-blockers", "Surgery", "Statins"],
  "apnea of prematurity": ["Caffeine citrate", "Ventilator support", "Oxygen therapy"],
  "arachnoiditis": ["Pain relievers", "Physical therapy", "Nerve blocks"],
  "aspergillosis": ["Antifungal drugs", "Corticosteroids", "Surgery"],
  "asthenia": ["Vitamin B complex", "Iron supplements", "Adaptogens"],
  "ataxia": ["Physical therapy", "Occupational therapy", "Anticonvulsants"],
  "atrial fibrillation": ["Beta-blockers", "Anticoagulants", "Cardioversion"],
  "autism spectrum disorder": ["Behavioral therapy", "SSRIs", "Antipsychotics"],
  "babesiosis": ["Antibiotics", "Antiparasitics", "Supportive care"],
  "bacterial vaginosis": ["Metronidazole", "Clindamycin", "Probiotics"],
  "barrett's esophagus": ["Proton pump inhibitors", "Endoscopic surveillance", "Surgery"],
  "behcet's disease": ["Corticosteroids", "Immunosuppressants", "Colchicine"],
  "beriberi": ["Thiamine supplements", "Dietary changes", "Vitamin B complex"],
  "biliary atresia": ["Kasai procedure", "Liver transplant", "Ursodiol"],
  "black hairy tongue": ["Antifungal mouthwash", "Tongue scraping", "Hydration"],
  "blastomycosis": ["Antifungal drugs", "Amphotericin B", "Itraconazole"],
  "bleeding disorders": ["Factor replacement therapy", "Desmopressin", "Antifibrinolytics"],
  "bone spurs": ["NSAIDs", "Corticosteroid injections", "Surgery"],
  "botulism": ["Antitoxin", "Ventilator support", "Antibiotics"],
  "brain abscess": ["Antibiotics", "Surgery", "Anticonvulsants"],
  "breast abscess": ["Antibiotics", "Incision and drainage", "Warm compresses"],
  "bronchiectasis": ["Bronchodilators", "Antibiotics", "Mucus thinners"],
  "brucellosis": ["Doxycycline", "Rifampin", "Gentamicin"],
  "bunion": ["Orthotics", "NSAIDs", "Surgery"],
  "burning mouth syndrome": ["Alpha-lipoic acid", "Clonazepam", "Vitamin B supplements"],
  "calciphylaxis": ["Wound care", "Sodium thiosulfate", "Parathyroidectomy"],
  "candidiasis": ["Antifungal drugs", "Probiotics", "Topical antifungals"],
  "carbon monoxide poisoning": ["Oxygen therapy", "Hyperbaric oxygen", "Supportive care"],
  "carcinoid syndrome": ["Somatostatin analogs", "Telotristat ethyl", "Surgery"],
  "cardiac arrest": ["CPR", "Defibrillation", "Epinephrine"],
  "cat scratch disease": ["Antibiotics", "Supportive care", "Pain relievers"],
  "celiac crisis": ["Gluten-free diet", "IV fluids", "Corticosteroids"],
  "cellulitis": ["Antibiotics", "Wound care", "Elevation"],
  "cerebral palsy": ["Physical therapy", "Muscle relaxants", "Orthopedic surgery"],
  "cervical dystonia": ["Botox injections", "Muscle relaxants", "Physical therapy"],
  "chagas disease": ["Antiparasitic drugs", "Supportive care", "Heart medications"],
  "chilblains": ["Nifedipine", "Topical corticosteroids", "Warm compresses"],
  "cholera": ["Oral rehydration salts", "Antibiotics", "Zinc supplements"],
  "chronic kidney disease": ["ACE inhibitors", "Diuretics", "Erythropoietin"],
  "chronic lymphocytic leukemia": ["Chemotherapy", "Targeted therapy", "Immunotherapy"],
  "chronic myelogenous leukemia": ["Tyrosine kinase inhibitors", "Chemotherapy", "Bone marrow transplant"],
  "chronic obstructive pulmonary disease": ["Bronchodilators", "Corticosteroids", "Oxygen therapy"],
  "chronic pancreatitis": ["Pancreatic enzymes", "Pain relievers", "Antioxidants"],
  "clostridium difficile infection": ["Vancomycin", "Fidaxomicin", "Probiotics"],
  "coarctation of the aorta": ["Surgery", "Beta-blockers", "Antihypertensives"],
  "cold agglutinin disease": ["Rituximab", "Blood transfusions", "Immunosuppressants"],
  "common variable immunodeficiency": ["IV immunoglobulin", "Antibiotics", "Vaccinations"],
  "congenital adrenal hyperplasia": ["Corticosteroids", "Mineralocorticoids", "Salt supplements"],
  "congestive heart failure": ["Diuretics", "ACE inhibitors", "Beta-blockers"],
  "coronary artery disease": ["Statins", "Beta-blockers", "Nitroglycerin"],
  "creutzfeldt-jakob disease": ["Supportive care", "Anticonvulsants", "Palliative care"],
  "croup": ["Dexamethasone", "Epinephrine", "Humidified air"],
  "cushing's syndrome": ["Ketoconazole", "Mifepristone", "Surgery"],
  "cyclic vomiting syndrome": ["Antiemetics", "Tricyclic antidepressants", "Hydration"],
  "cystitis": ["Antibiotics", "Pain relievers", "Hydration"],
  "dengue fever": ["Supportive care", "Hydration", "Antipyretics"],
  "dermatomyositis": ["Corticosteroids", "Immunosuppressants", "Physical therapy"],
  "diabetic ketoacidosis": ["Insulin", "IV fluids", "Electrolyte replacement"],
  "diphtheria": ["Antitoxin", "Antibiotics", "Vaccination"],
  "disseminated intravascular coagulation": ["Blood transfusions", "Anticoagulants", "Supportive care"],
  "down syndrome": ["Early intervention", "Physical therapy", "Speech therapy"],
  "dumping syndrome": ["Dietary changes", "Acarbose", "Octreotide"],
  "dysautonomia": ["Fludrocortisone", "Midodrine", "Compression stockings"],
  "dyshidrotic eczema": ["Topical corticosteroids", "Antihistamines", "Phototherapy"],
  "eclampsia": ["Magnesium sulfate", "Antihypertensives", "Delivery"],
  "ectopic pregnancy": ["Methotrexate", "Surgery", "Supportive care"],
  "ehlers-danlos syndrome": ["Physical therapy", "Pain relievers", "Bracing"],
  "empyema": ["Antibiotics", "Chest tube drainage", "Surgery"],
  "encephalitis": ["Antiviral drugs", "Corticosteroids", "Supportive care"],
  "endocarditis": ["Antibiotics", "Surgery", "Anticoagulants"],
  "eosinophilic esophagitis": ["Topical steroids", "Dietary changes", "PPIs"],
  "eosinophilic pneumonia": ["Corticosteroids", "Antifungal drugs", "Supportive care"],
  "epididymitis": ["Antibiotics", "Pain relievers", "Scrotal support"],
  "erythema multiforme": ["Antihistamines", "Corticosteroids", "Supportive care"],
  "erythema nodosum": ["NSAIDs", "Corticosteroids", "Potassium iodide"],
  "esophagitis": ["PPIs", "Antacids", "Dietary changes"],
  "essential tremor": ["Propranolol", "Primidone", "Deep brain stimulation"],
  "fabry disease": ["Enzyme replacement therapy", "Pain relievers", "ACE inhibitors"],
  "familial mediterranean fever": ["Colchicine", "Interleukin-1 inhibitors", "Supportive care"],
  "fanconi anemia": ["Androgens", "Bone marrow transplant", "Growth factors"],
  "fascioliasis": ["Triclabendazole", "Antibiotics", "Supportive care"],
  "felty syndrome": ["Methotrexate", "Rituximab", "Splenectomy"],
  "fibrous dysplasia": ["Bisphosphonates", "Surgery", "Pain relievers"],
  "fifth disease": ["Supportive care", "Antipyretics", "Hydration"],
  "filariasis": ["Antiparasitic drugs", "Antibiotics", "Surgery"],
  "focal segmental glomerulosclerosis": ["Corticosteroids", "Immunosuppressants", "ACE inhibitors"],
  "folliculitis": ["Antibiotics", "Antifungal drugs", "Topical antiseptics"],
  "fragile x syndrome": ["Behavioral therapy", "SSRIs", "Speech therapy"],
  "frostbite": ["Rewarming", "Pain relievers", "Wound care"],
  "galactorrhea": ["Dopamine agonists", "Surgery", "Hormonal therapy"],
  "gangrene": ["Antibiotics", "Surgery", "Hyperbaric oxygen therapy"],
  "gastroparesis": ["Metoclopramide", "Dietary changes", "Electrical stimulation"],
  "giardiasis": ["Metronidazole", "Tinidazole", "Nitazoxanide"],
  "gilbert's syndrome": ["Supportive care", "Hydration", "Avoid fasting"],
  "glossitis": ["Vitamin B supplements", "Antibiotics", "Topical corticosteroids"],
  "goodpasture syndrome": ["Immunosuppressants", "Plasmapheresis", "Corticosteroids"],
  "granuloma annulare": ["Topical corticosteroids", "Cryotherapy", "Phototherapy"],
  "guillain-barre syndrome": ["IV immunoglobulin", "Plasmapheresis", "Supportive care"],
  "haemochromatosis": ["Phlebotomy", "Iron chelation", "Dietary changes"],
  "haemophilia": ["Factor replacement therapy", "Desmopressin", "Antifibrinolytics"],
  "hantavirus pulmonary syndrome": ["Supportive care", "Oxygen therapy", "Ribavirin"],
  "hashimoto's thyroiditis": ["Levothyroxine", "Selenium", "Dietary changes"],
  "hemolytic uremic syndrome": ["Plasma exchange", "Dialysis", "Supportive care"],
  "henoch-schonlein purpura": ["Corticosteroids", "NSAIDs", "Supportive care"],
  "hepatic encephalopathy": ["Lactulose", "Rifaximin", "Dietary changes"],
  "hepatitis a": ["Supportive care", "Hydration", "Vaccination"],
  "hepatitis e": ["Supportive care", "Hydration", "Ribavirin"],
  "hereditary angioedema": ["C1 esterase inhibitors", "Icatibant", "Tranexamic acid"],
  "hiatal hernia": ["PPIs", "Antacids", "Surgery"],
  "histoplasmosis": ["Antifungal drugs", "Amphotericin B", "Itraconazole"],
  "huntington's disease": ["Tetrabenazine", "Antipsychotics", "Supportive care"],
  "hydronephrosis": ["Stent placement", "Surgery", "Antibiotics"],
  "hyperemesis gravidarum": ["Antiemetics", "IV fluids", "Vitamin B6"],
  "hyperparathyroidism": ["Surgery", "Cinacalcet", "Bisphosphonates"],
  "hypersplenism": ["Splenectomy", "Immunosuppressants", "Supportive care"],
  "hypocalcemia": ["Calcium supplements", "Vitamin D", "Magnesium"],
  "hypoglycemia": ["Glucose tablets", "Glucagon", "Dietary changes"],
  "hypoparathyroidism": ["Calcium supplements", "Vitamin D", "Parathyroid hormone"],
  "hypophosphatasia": ["Enzyme replacement therapy", "Pain relievers", "Physical therapy"],
  "hypopituitarism": ["Hormone replacement therapy", "Corticosteroids", "Levothyroxine"],
  "hypothermia": ["Rewarming", "Warm IV fluids", "Supportive care"],
  "idiopathic intracranial hypertension": ["Acetazolamide", "Topiramate", "Surgery"],
  "idiopathic pulmonary fibrosis": ["Pirfenidone", "Nintedanib", "Oxygen therapy"],
  "iga nephropathy": ["Corticosteroids", "ACE inhibitors", "Immunosuppressants"],
  "impetigo": ["Topical antibiotics", "Oral antibiotics", "Antiseptics"],
  "interstitial cystitis": ["Pentosan polysulfate", "Amitriptyline", "Bladder instillations"],
  "intestinal obstruction": ["Nasogastric tube", "Surgery", "IV fluids"],
  "iron deficiency anemia": ["Iron supplements", "Vitamin C", "Dietary changes"],
  "kawasaki disease": ["IV immunoglobulin", "Aspirin", "Corticosteroids"],
  "keratoconus": ["Rigid contact lenses", "Corneal cross-linking", "Surgery"],
  "klinefelter syndrome": ["Testosterone therapy", "Speech therapy", "Educational support"],
  "legionnaires' disease": ["Antibiotics", "Supportive care", "Oxygen therapy"],
  "leishmaniasis": ["Antimonial drugs", "Amphotericin B", "Miltefosine"],
  "leptospirosis": ["Antibiotics", "Supportive care", "Hydration"],
  "lichen planus": ["Topical corticosteroids", "Antihistamines", "Phototherapy"],
  "listeriosis": ["Antibiotics", "Supportive care", "Hydration"],
  "lung abscess": ["Antibiotics", "Drainage", "Surgery"],
  "lupus nephritis": ["Corticosteroids", "Immunosuppressants", "ACE inhibitors"],
  "lymphangitis": ["Antibiotics", "Warm compresses", "Elevation"],
  "lymphoma": ["Chemotherapy", "Radiation therapy", "Immunotherapy"],
  "malabsorption syndrome": ["Dietary changes", "Vitamin supplements", "Enzyme replacement"],
  "mastitis": ["Antibiotics", "Warm compresses", "Pain relievers"],
  "mccune-albright syndrome": ["Bisphosphonates", "Surgery", "Hormonal therapy"],
  "mediastinitis": ["Antibiotics", "Surgery", "Supportive care"],
  "meningitis": ["Antibiotics", "Antivirals", "Corticosteroids"],
  "meniere's disease": ["Diuretics", "Antihistamines", "Vestibular rehab"],
  "mesothelioma": ["Chemotherapy", "Radiation therapy", "Surgery"],
  "metabolic syndrome": ["Lifestyle changes", "Metformin", "Statins"],
  "molluscum contagiosum": ["Cryotherapy", "Topical treatments", "Curettage"],
  "mountain sickness": ["Acetazolamide", "Dexamethasone", "Oxygen therapy"],
  "mucormycosis": ["Antifungal drugs", "Surgery", "Supportive care"],
  "multiple endocrine neoplasia": ["Surgery", "Hormonal therapy", "Supportive care"],
  "myasthenia gravis": ["Pyridostigmine", "Immunosuppressants", "Plasmapheresis"],
  "mycoplasma pneumonia": ["Antibiotics", "Supportive care", "Oxygen therapy"],
  "myelodysplastic syndrome": ["Chemotherapy", "Blood transfusions", "Bone marrow transplant"],
  "myocarditis": ["Corticosteroids", "Immunosuppressants", "Supportive care"],
  "narcolepsy": ["Stimulants", "Sodium oxybate", "Antidepressants"],
  "necrotizing fasciitis": ["Antibiotics", "Surgery", "Hyperbaric oxygen"],
  "nephrotic syndrome": ["Corticosteroids", "Immunosuppressants", "Diuretics"],
  "neurofibromatosis": ["Surgery", "Pain relievers", "Physical therapy"],
  "neutropenia": ["Granulocyte colony-stimulating factor", "Antibiotics", "Supportive care"],
  "nocardiosis": ["Antibiotics", "Surgery", "Supportive care"],
  "norovirus infection": ["Hydration", "Antiemetics", "Supportive care"],
  "obstructive sleep apnea": ["CPAP machine", "Oral appliances", "Surgery"],
  "onychomycosis": ["Antifungal drugs", "Topical treatments", "Laser therapy"],
  "breast cancer": ["Tamoxifen", "Letrozole", "Trastuzumab", "Paclitaxel", "Doxorubicin"],
  "lung cancer": ["Cisplatin", "Erlotinib", "Pembrolizumab", "Nivolumab", "Paclitaxel"],
  "prostate cancer": ["Leuprolide", "Bicalutamide", "Docetaxel", "Abiraterone", "Enzalutamide"],
  "leukemia": ["Imatinib", "Dasatinib", "Vincristine", "Methotrexate", "Cytarabine"],
  "colorectal cancer": ["Fluorouracil", "Bevacizumab", "Oxaliplatin", "Irinotecan", "Capecitabine"],
  "liver cancer": ["Sorafenib", "Lenvatinib", "Regorafenib", "Nivolumab"],
  "ovarian cancer": ["Carboplatin", "Paclitaxel", "Olaparib", "Bevacizumab"],
  "pancreatic cancer": ["Gemcitabine", "Erlotinib", "Fluorouracil", "Nab-Paclitaxel"],
  "brain cancer": ["Temozolomide", "Bevacizumab", "Lomustine", "Vincristine"],
  "skin cancer": ["Vemurafenib", "Ipilimumab", "Nivolumab", "Dabrafenib"],
  "cancer": ["Cisplatin", "Doxorubicin", "Pembrolizumab", "Nivolumab", "Trastuzumab", "Bevacizumab"]
};
